#!/usr/bin/env python3

from subprocess import call, run
import re
from time import perf_counter

files = ["21.png"]

with open("results.csv", "w", 1) as results:
    results.write("image,qtable,quality,size,time,butteraugli\n")
    for f in files:
        for quality in range(0,90,5):
            for qtable in ["3","6"]:
                infile = "kodak/kodim" + f
                outfile = "output/" + f.replace(".png", f"-{qtable}-{quality}.jpg")
                print(f"Beginning encode for {outfile}")
                start = perf_counter()

                output = run(
                    [
                        "./cjpeg",
                        "-quality",
                        f"{quality}",
                        "-quant-table",
                        qtable,
                        "-outfile",
                        outfile,
                        infile,
                    ],
                    capture_output=True,
                )

                psnr = run(
                    ["butteraugli", infile, outfile],
                    capture_output=True,
                )

                psnr = float(psnr.stdout.decode("utf8"))

                size = int(
                    run(
                        ["stat", "--format", "%s", outfile], capture_output=True
                    ).stdout.decode("utf8")
                )

                time = perf_counter() - start

                print(f"{infile} {qtable} {size} {time} {psnr}")

                results.write(
                    f"{infile},{qtable},{quality},{size},{time:.2f},{psnr:.2f}\n"
                )
